### ISSUE TITLE
/faucet error caused server freeze

### ISSUE THREAD

**Issue by Ale32bit** [Lemmmy/KristPay2#5]
A player ran `/faucet`, this happened and froze the entire server:
```
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at pw.lemmmy.kristpay.database.FaucetReward.add(FaucetReward.java:52)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at pw.lemmmy.kristpay.economy.FaucetManager.redeem(FaucetManager.java:58)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at pw.lemmmy.kristpay.commands.CommandFaucet.execute(CommandFaucet.java:61)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:338)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:192)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zko000(SourceFile:540)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:5215)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                                     [23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                               [23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                        [23:21:55] [Server thread/INFO] [STDERR]: [pw.lemmmy.kristpay.database.FaucetReward:add:63]:    at java.lang.Thread.run(Thread.java:748)  
```

**Comment by lurr** [comment]
This is caused by a database timeout - check your database, as the issue lies there.
